### PR TITLE
Adding V3.4.1

### PR DESCRIPTION
**Pull request by imohamme**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by imohamme** [comment]
@conda-forge-admin, please rerender

**Comment by imohamme** [comment]
@conda-forge-admin, please rerender

**Review by mfansler — APPROVED** [review]
This looks good to merge.

I'll note that typically only the `Imports` and `Depends` packages should be added as requirements, which would be consistent with how R itself behaves. However, this package currently also has some `Suggests` packages listed as host/runtime requirements. Since you are the upstream author, I'd say it's your call, but it is a bit inconsistent. The recipe should work without `r-ggmap`, `r-ggplot2`, `r-sf`, `r-getpass`, `r-codetools`.

**Comment by imohamme** [comment]
Thanks, I want to close this PR and add a new one that takes care of your comments.

**Pull request closed without merging**
